import json
from typing import Dict, Any
from app.reporting.schema import Report


class ReportFormatter:
    def format_json(self, report: Report) -> str:
        return json.dumps(
            report.model_dump(),
            indent=2,
            default=str
        )

    def format_html(self, report: Report) -> str:
        html = f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{report.title}</title>
    <style>
        body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; 
               max-width: 900px; margin: 0 auto; padding: 20px; background: #0b1326; color: #dae2fd; }}
        h1 {{ color: #b9c7e0; border-bottom: 1px solid #45464d; padding-bottom: 10px; }}
        h2 {{ color: #6bd8cb; margin-top: 30px; }}
        .summary {{ background: #171f33; padding: 15px; border-radius: 8px; margin: 20px 0; }}
        .insight {{ background: #222a3d; padding: 12px; margin: 10px 0; border-radius: 6px; border-left: 3px solid #6bd8cb; }}
        .confidence-high {{ border-left-color: #6bd8cb; }}
        .confidence-medium {{ border-left-color: #ffb95f; }}
        .confidence-low {{ border-left-color: #ffb4ab; }}
        .confidence {{ font-size: 12px; color: #909097; }}
        .plot {{ margin: 20px 0; }}
        .plot img {{ max-width: 100%; border-radius: 8px; }}
        .stats {{ display: grid; grid-template-columns: repeat(4, 1fr); gap: 10px; margin: 20px 0; }}
        .stat {{ background: #171f33; padding: 15px; border-radius: 8px; text-align: center; }}
        .stat-value {{ font-size: 24px; font-weight: bold; color: #b9c7e0; }}
        .stat-label {{ font-size: 12px; color: #909097; }}
        .footer {{ margin-top: 40px; padding-top: 20px; border-top: 1px solid #45464d; 
                  font-size: 12px; color: #909097; }}
    </style>
</head>
<body>
    <h1>{report.title}</h1>
    <p>Generated: {report.generated_at}</p>
    
    <div class="summary">
        <h2>Summary</h2>
        <p>{report.summary}</p>
    </div>
    
    <div class="stats">
        <div class="stat">
            <div class="stat-value">{len(report.insights)}</div>
            <div class="stat-label">Insights</div>
        </div>
        <div class="stat">
            <div class="stat-value">{len(report.plots)}</div>
            <div class="stat-label">Plots</div>
        </div>
        <div class="stat">
            <div class="stat-value">{report.stats.get('columns', 0)}</div>
            <div class="stat-label">Columns</div>
        </div>
        <div class="stat">
            <div class="stat-value">{len(report.predictions)}</div>
            <div class="stat-label">Predictions</div>
        </div>
    </div>
    
    <h2>Key Insights</h2>
"""

        for idx, insight in enumerate(report.insights, 1):
            confidence = insight.get("confidence", 0)
            if confidence >= 0.75:
                conf_class = "confidence-high"
            elif confidence >= 0.5:
                conf_class = "confidence-medium"
            else:
                conf_class = "confidence-low"

            html += f"""
    <div class="insight {conf_class}">
        <p>{insight.get('insight', 'N/A')}</p>
        <p class="confidence">Confidence: {confidence*100:.0f}% | Type: {insight.get('type', 'N/A')}</p>
    </div>
"""

        html += """
    <h2>Visualizations</h2>
"""

        for plot in report.plots:
            if plot.get("format") == "base64_png" and plot.get("data"):
                html += f"""
    <div class="plot">
        <p>{plot.get('title', 'Visualization')}</p>
        <img src="data:image/png;base64,{plot.get('data')}" alt="Plot"/>
    </div>
"""
            else:
                html += f"""
    <div class="plot">
        <p>{plot.get('title', 'Plot')} ({plot.get('type', 'unknown')})</p>
    </div>
"""

        html += f"""
    <div class="footer">
        <p>Report generated by Data Analyst Agent | Session: {report.stats.get('session_id', 'N/A')}</p>
    </div>
</body>
</html>
"""
        return html
